local config = {}

local function serialize(value, indent, seen)
  local kind = type(value)
  if kind == "string" then return string.format("%q", value) end
  if kind == "number" or kind == "boolean" then return tostring(value) end
  if kind ~= "table" then error("cannot save config value of type " .. kind) end
  seen = seen or {}
  assert(not seen[value], "cannot save a config containing a table cycle")
  seen[value] = true
  indent = indent or 0

  local count, maximum, array = 0, 0, true
  for key in pairs(value) do
    count = count + 1
    if type(key) ~= "number" or key < 1 or key % 1 ~= 0 then
      array = false
    else
      maximum = math.max(maximum, key)
    end
  end
  array = array and maximum == count

  local lines, padding, childPadding = { "{" }, string.rep("  ", indent),
    string.rep("  ", indent + 1)
  if array then
    for index = 1, maximum do
      lines[#lines + 1] = childPadding .. serialize(value[index], indent + 1, seen) .. ","
    end
  else
    local keys = {}
    for key in pairs(value) do keys[#keys + 1] = key end
    table.sort(keys, function(left, right) return tostring(left) < tostring(right) end)
    for _, key in ipairs(keys) do
      local encodedKey
      if type(key) == "string" and key:match("^[%a_][%w_]*$") then
        encodedKey = key
      else
        encodedKey = "[" .. serialize(key, indent + 1, seen) .. "]"
      end
      lines[#lines + 1] = childPadding .. encodedKey .. " = " ..
        serialize(value[key], indent + 1, seen) .. ","
    end
  end
  lines[#lines + 1] = padding .. "}"
  seen[value] = nil
  return table.concat(lines, "\n")
end

local function fileOperations()
  if type(fs) == "table" and type(fs.move) == "function" then
    return fs.exists, fs.delete, function(source, destination)
      local ok, err = pcall(fs.move, source, destination)
      return ok, err
    end
  end
  local ok, filesystem = pcall(require, "filesystem")
  if ok then
    return filesystem.exists, filesystem.remove, filesystem.rename
  end
  local function exists(path)
    local file = io.open(path, "rb")
    if file then file:close() return true end
    return false
  end
  return exists, os.remove, os.rename
end

function config.load(path)
  path = path or "/etc/ducknet/config.lua"
  local chunk, err = loadfile(path)
  if not chunk then return nil, err end
  local ok, value = pcall(chunk)
  if not ok then return nil, value end
  if type(value) ~= "table" then return nil, "config must return a table" end
  return value
end

function config.save(value, path)
  path = path or "/etc/ducknet/config.lua"
  local body = "-- Generated by DuckNet.\nreturn " .. serialize(value, 0) .. "\n"
  local temporary, backup = path .. ".ducknet-new", path .. ".ducknet-old"
  local file, err = io.open(temporary, "w")
  if not file then return nil, err end
  local ok, writeError = pcall(function() file:write(body) end)
  file:close()
  if not ok then return nil, writeError end

  local exists, remove, rename = fileOperations()
  if exists(backup) then remove(backup) end
  local hadOriginal = exists(path)
  if hadOriginal then
    local moved, moveError = rename(path, backup)
    if not moved then remove(temporary) return nil, moveError end
  end
  local installed, installError = rename(temporary, path)
  if not installed then
    if hadOriginal then rename(backup, path) end
    return nil, installError
  end
  if hadOriginal and exists(backup) then remove(backup) end
  return true
end

return config
